### ISSUE TITLE
Too slow for long lisp function (530 line of lisp function/method definition)

### ISSUE THREAD

**Issue by chunsj** [Malabarba/aggressive-indent-mode#58] opened 2015-09-10 12:10 UTC
Can I set timeout if it takes too long (> 2 secs) the aggressive indentation could be off?

**Comment by Malabarba** [comment] 2015-09-13 14:43
There's no way to do that currently.
One thing you could do is just disable aggressive-indent in that file via  file-local variable.

But why do you feel the need to do this? The mode is designed to not hang the interface while it does its thing.
Are you experiencing hangs?

**Comment by chunsj** [comment] 2015-09-14 00:50
Yes, for large file, in my macbook pro retina 13 (2014 mid), it takes very long to type even single character.
As your suggestion, I've disabled aggressive-indent for those files, however, I miss them :-)

**Comment by Malabarba** [comment] 2015-09-15 18:14
Just out of curiosity. What package version are you on?

**Comment by chunsj** [comment] 2015-09-15 21:34
Latest one from melpa.

**Comment by manuel-uberti** [comment] 2015-10-16 08:33
This happens to me as well. Latest `aggressive-indent-mode` from MELPA and Emacs `25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.2) of 2015-10-16`.

**Comment by Malabarba** [comment] 2015-10-16 09:23
I'll try to figure out a better to avoid hanging. In the meantime, the best solution is to disable it in a file-local var.

**Comment by manuel-uberti** [comment] 2015-10-16 09:31
Oh, yes, I'm just turning it off in some elisp files for now with `M-x aggressive-indent-mode`.

**Comment by Malabarba** [comment] 2015-10-16 09:47
:) :+1:

**Comment by unbalancedparentheses** [comment] 2015-12-24 15:54
I have the same issue with big erlang files. The interface hangs while having aggressive indent mode enabled.

**Comment by Malabarba** [comment] 2016-07-11 00:44
Closing as duplicate of #73

**Closed** 2016-07-11 00:44 UTC
