### ISSUE TITLE
Agressive-indent-mode does not correctly unindent

### ISSUE THREAD

**Issue by kahrkunne** [Malabarba/aggressive-indent-mode#89] opened 2016-06-22 19:34 UTC
See attached gif. Tested on Linux and Windows, by two different people, using the same code (this code: https://gist.github.com/reasv/b3c5794d1070b77eea7126921a0b0c2f)

![agg_ind_bug](https://cloud.githubusercontent.com/assets/6626453/16280639/eea17154-38c0-11e6-9b4c-cf0bde961334.gif)

**Comment by mattiasb** [comment] 2016-06-22 21:49
It /might/ have to do with the syntax error on [line 19](https://gist.github.com/reasv/b3c5794d1070b77eea7126921a0b0c2f#file-meme-js-L19).

This is what I get fwiw: [screencast](https://www.youtube.com/watch?v=YU5MrLAC2ac&feature=youtu.be)

**Comment by Malabarba** [comment] 2016-07-06 00:00
@kahrkunne I can't reproduce that here. Are you on a stable release? If so Could you try updating to the latest snapshot?

**Comment by Malabarba** [comment] 2016-10-12 20:46
I've just pushed some logic that improves the decision of when to unindent. Since this has gone without answer, I'll close it for now and people can report new bugs if they run into anything.

**Closed by Malabarba** 2016-10-12 20:46 UTC
