### ISSUE TITLE
Performance issue with an Erlang file with 3k lines

### ISSUE THREAD

**Issue by unbalancedparentheses** [Malabarba/aggressive-indent-mode#71] opened 2016-02-12 20:33 UTC
It is really painful to edit an Erlang file with 3k lines when having aggressive indent mode enabled. It hangs the interface, adding an enter takes a lot of time.

**Comment by Malabarba** [comment] 2016-02-13 10:46
Do you have a link to a sample file that causes this? It's unlikely that this can be fixed on aggressive-indent-mode, but it's possible I can pinpoint the cause.

**Comment by unbalancedparentheses** [comment] 2016-02-13 23:18
I have sent you an email with a link to it. It is private code of a client.

**Comment by Malabarba** [comment] 2016-07-11 00:12
Sorry for not replying. Looks like this issue got lost in my todo-list. I tried your link today but it's down now (which is to be expected, given how long it took me to get to it).
Is this still an issue for you?

**Closed** 2016-10-12 19:31 UTC
Labels: in progress, performance
